version: '3.4'

configs:
  bf_config:
    file: ./config.php
  haproxy_config:
    file: ./haproxy.cfg


services:
  app:
    image: mcnutty/drift2.0:latest
    volumes:
      - /images:/var/www/html/images
    environment:
      # Port used by the HAProxy to reach the service.
      - SERVICE_PORTS=80
      - MEMCACHE_SERVER=memcache
    deploy:
      replicas: 5
      restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
    #  placement:
    #    constraints: [node.role != manager]
    #### tester med dette av ####
    networks:
      - web
    depends_on:
      - memcache
    ports:
      - 80:80

    configs:
      - source: bf_config
        target: /var/www/html/config.php
    networks:
        - web
    environment:
      BF_MEMCACHE_SERVER: memcache

  memcache:
    image: memcached
    deploy:
      replicas: 1

    networks:
      - web

  db-proxy:
    image: haproxy:alpine # The official Traefik docker image

    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg

    networks:
      - web

    deploy:
      mode: global

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8989:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
    networks:
      - web

  cockroachdb-1:
     image: cockroachdb/cockroach:v2.1.6
     command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure --temp-dir=/tmp --store=/mnt
     ports:
       - "8082:8080"
     networks:
       - web
     deploy:
      replicas: 1
     volumes:
           - codb-1:/mnt

  cockroachdb-2:
     image: cockroachdb/cockroach:v2.1.6
     command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure --temp-dir=/tmp
     networks:
       - web
     deploy:
      replicas: 1
     volumes:
           - codb-2:/cockroach/cockroach-data

  cockroachdb-3:
     image: cockroachdb/cockroach:v2.1.6
     command: start --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr --insecure --temp-dir=/tmp
     networks:
       - web
     deploy:
      replicas: 1
     volumes:
           - codb-3:/cockroach/cockroach-data

volumes:
  codb-3:
    driver: glusterfs
    driver_opts:
      servers: 192.168.128.228,192.168.128.168,192.168.129.25
    name: "db3"
  codb-2:
    driver: glusterfs
    driver_opts:
      servers: 192.168.128.228,192.168.128.168,192.168.129.25
    name: "db2"
  codb-1:
    driver: glusterfs
    driver_opts:
      servers: 192.168.128.228,192.168.128.168,192.168.129.25
    name: "db1"

networks:
  web:
    driver: overlay
    attachable: true
